### ISSUE TITLE
S3 - softer options: make it be able to consume ENV instead of every param passed in query

### ISSUE THREAD

**Issue by mxmCherry** [bsm/bfs.rb#1]
https://github.com/bsm/bfs.rb/blob/master/s3/lib/bfs/bucket/s3.rb#L159

```ruby
BFS.register('s3') do |url|
  params = CGI.parse(url.query.to_s)

  BFS::Bucket::S3.new url.host,
    region: params.key?('region') ? params['region'].first : nil,
    sse: params.key?('sse') ? params['sse'].first : nil,
    access_key_id: params.key?('access_key_id') ? params['access_key_id'].first : nil,
    secret_access_key: params.key?('secret_access_key') ? params['secret_access_key'].first : nil,
    acl: params.key?('acl') ? params['acl'].first : nil,
    storage_class: params.key?('storage_class') ? params['storage_class'].first : nil
end
```

I'd say, let's do smth like `attrs.compact` there?

This way, it will be consistent with AWS gem(s), which can accept ENV vars like access/secret key.

I can PR it (but without the `.compact` method unless activesupport is included here), should I?

**Comment by dim** [comment]
The initialiser symbolizes keys and deletes all nil values anyway, see https://github.com/bsm/bfs.rb/blob/master/s3/lib/bfs/bucket/s3.rb#L30, it's line https://github.com/bsm/bfs.rb/blob/master/s3/lib/bfs/bucket/s3.rb#L150 which needs the `compact`

**Comment by mxmCherry** [comment]
Oh, right, sorry - haven't checked it carefully.
