### ISSUE TITLE
AWS file uploads are never abandoned when local writing fails

### ISSUE THREAD

**Issue by vrih** [bsm/bfs.rb#24]
When writing a file for upload to S3 exceptions in the file writing process are ignored, causing incomplete files to be uploaded to S3. Unless specifically requested otherwise, e.g. for a stream writer where getting some data up is better than no data,  any exception in the Tempwriter should cause feed upload to be abandoned.

https://github.com/bsm/bfs.rb/blob/master/s3/lib/bfs/bucket/s3.rb#L94

There is also similar logic in FeedX so it may be that this needs to be fixed in 2 places.

**Comment by vrih** [comment]
It appears that the on success this now fails because we try to unlink an already closed Tempfile. If https://github.com/bsm/bfs.rb/blob/a7caf87c934a8d99f5c15a7c2ce546f602d9e2df/core/lib/bfs/helpers.rb#L26 is closed? then the ensure block will always raise an exception.

**Comment by dim** [comment]
> It appears that the on success this now fails because we try to unlink an already closed Tempfile. If
> 
> https://github.com/bsm/bfs.rb/blob/a7caf87c934a8d99f5c15a7c2ce546f602d9e2df/core/lib/bfs/helpers.rb#L26
> is closed? then the ensure block will always raise an exception.

@vrih do you have an example or a backtrace, I cannot recreate an error in tests/console
