### ISSUE TITLE
SCP.ls returning erroneous results on large responses

### ISSUE THREAD

**Issue by vrih** [bsm/bfs.rb#28]
When stdout returns a large amount of data it may be split into multiple `on_data` responses. When that happens a line may be split between 2 on_data calls. We're processing each of these blocks individually, which causes us to have unexpected data at the boundaries. We will likely need to buffer the data and only process based on newline boundaries.

**Comment by dim** [comment]
@mxmCherry do you mind taking a look at this when free?
